language: node_js
node_js:
  - "12"
dist: trusty
sudo: required
branches:
  only:
  - master
script:
- npm run lint
- npm run test-headless
- npm run build -- --prod --base-href /elandyg-angular/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/elandyg-angular
  on:
    branch: master
